name: Subir HTML diario desde Google Drive

on:
  schedule:
    - cron: '0 17 * * *'  # Todos los días a las 14:00 hora Argentina (17:00 UTC)
  workflow_dispatch:

jobs:
  actualizar-html:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Descargar HTML desde Google Drive
        run: curl -L "https://drive.google.com/uc?export=download&id=1S5Lrv0UO4C5MQ44RoF7YEFsDC5l4Y8g-" -o eventos_hoy.html

      - name: Hacer commit si hay cambios
        run: |
          git config --local user.email "bot@github.com"
          git config --local user.name "GitHub Action"
          git add eventos_hoy.html
          git commit -m "Actualización diaria de eventos_hoy.html" || echo "Sin cambios"
          git push
